[build]
  publish = ".output/public"
  command = "bun run build"

[build.environment]
  NODE_VERSION = "22"
  BUN_VERSION = "1.1.38"

# SPA routing for SolidStart
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Form handling
[forms]
  # Enable form detection
  enabled = true

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Functions (if needed later)
[functions]
  directory = "netlify/functions"
